/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecreciclaje;

/**
 *
 * @author valer
 */
public class OtrasOpcionesReciclar extends javax.swing.JFrame {

    /**
     * Creates new form OtrasOpcionesReciclar
     */
    public OtrasOpcionesReciclar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Panel_Ingresar_Material = new javax.swing.JPanel();
        Tex_Cuantas_Piezas = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        Text_Que_Material = new javax.swing.JLabel();
        Material = new javax.swing.JTextField();
        Boton_Agregar = new javax.swing.JButton();
        Text_Ingresar_Material = new javax.swing.JLabel();
        Imagen_Mascota_Pensativo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 221, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 610));

        jPanel2.setBackground(new java.awt.Color(33, 124, 97));
        jPanel2.setPreferredSize(new java.awt.Dimension(760, 67));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        Panel_Ingresar_Material.setBackground(new java.awt.Color(232, 245, 224));

        Tex_Cuantas_Piezas.setBackground(new java.awt.Color(51, 107, 5));
        Tex_Cuantas_Piezas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Tex_Cuantas_Piezas.setForeground(new java.awt.Color(27, 94, 32));
        Tex_Cuantas_Piezas.setText("¿Cuantás piezas tienes?");

        Cantidad.setBackground(new java.awt.Color(255, 255, 255));
        Cantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Text_Que_Material.setBackground(new java.awt.Color(51, 107, 5));
        Text_Que_Material.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Text_Que_Material.setForeground(new java.awt.Color(27, 94, 32));
        Text_Que_Material.setText("¿Qué material deseas reciclar?");

        Material.setBackground(new java.awt.Color(255, 255, 255));
        Material.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Material.setForeground(new java.awt.Color(0, 0, 0));
        Material.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Material.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Boton_Agregar.setBackground(new java.awt.Color(46, 125, 50));
        Boton_Agregar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Boton_Agregar.setForeground(new java.awt.Color(0, 0, 0));
        Boton_Agregar.setText("Agregar");
        Boton_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_AgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_Ingresar_MaterialLayout = new javax.swing.GroupLayout(Panel_Ingresar_Material);
        Panel_Ingresar_Material.setLayout(Panel_Ingresar_MaterialLayout);
        Panel_Ingresar_MaterialLayout.setHorizontalGroup(
            Panel_Ingresar_MaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                .addGroup(Panel_Ingresar_MaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Material, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(Boton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Text_Que_Material, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Tex_Cuantas_Piezas)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Panel_Ingresar_MaterialLayout.setVerticalGroup(
            Panel_Ingresar_MaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Ingresar_MaterialLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Text_Que_Material)
                .addGap(18, 18, 18)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tex_Cuantas_Piezas)
                .addGap(18, 18, 18)
                .addComponent(Material, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Boton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        Text_Ingresar_Material.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Text_Ingresar_Material.setForeground(new java.awt.Color(27, 94, 32));
        Text_Ingresar_Material.setText("¡Ingresa los datos del material!");

        Imagen_Mascota_Pensativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MascotaPensativor.png"))); // NOI18N
        Imagen_Mascota_Pensativo.setText("jLabel4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Flecharegreso..png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Panel_Ingresar_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Imagen_Mascota_Pensativo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Text_Ingresar_Material, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(Text_Ingresar_Material, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Imagen_Mascota_Pensativo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Ingresar_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AgregarMouseClicked
        // TODO add your handling code here:
       PantallaOtroExito exito = new PantallaOtroExito ();
       exito.setVisible(true);
       dispose();
    }//GEN-LAST:event_Boton_AgregarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       Reciclaje regreso = new Reciclaje ();
       regreso.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtrasOpcionesReciclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtrasOpcionesReciclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtrasOpcionesReciclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtrasOpcionesReciclar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtrasOpcionesReciclar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agregar;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JLabel Imagen_Mascota_Pensativo;
    private javax.swing.JTextField Material;
    private javax.swing.JPanel Panel_Ingresar_Material;
    private javax.swing.JLabel Tex_Cuantas_Piezas;
    private javax.swing.JLabel Text_Ingresar_Material;
    private javax.swing.JLabel Text_Que_Material;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
