/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecreciclaje;

/**
 *
 * @author valer
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla2
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        basura = new javax.swing.JLabel();
        LogrosBoton = new javax.swing.JButton();
        MiHistorialBoton = new javax.swing.JButton();
        TiendaBoton = new javax.swing.JButton();
        UsuarioPuntos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Mascota = new javax.swing.JLabel();
        LadoOjitasDerecho = new javax.swing.JLabel();
        LadoOjitasIzquierdo = new javax.swing.JLabel();
        MensajeLogros = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 221, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reciclaje 2.png"))); // NOI18N
        basura.setText("BotonReciclaje");
        basura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basuraMouseClicked(evt);
            }
        });
        jPanel1.add(basura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 220, -1));

        LogrosBoton.setBackground(new java.awt.Color(51, 107, 5));
        LogrosBoton.setText("🍃Logros");
        LogrosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogrosBotonActionPerformed(evt);
            }
        });
        jPanel1.add(LogrosBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 151, 64));

        MiHistorialBoton.setBackground(new java.awt.Color(51, 107, 5));
        MiHistorialBoton.setText("🍃Mi Historial");
        MiHistorialBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiHistorialBotonActionPerformed(evt);
            }
        });
        jPanel1.add(MiHistorialBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 151, 64));

        TiendaBoton.setBackground(new java.awt.Color(51, 107, 5));
        TiendaBoton.setText("🍃Tienda");
        jPanel1.add(TiendaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 151, 64));

        UsuarioPuntos.setBackground(new java.awt.Color(33, 124, 97));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario_181");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("🍃218");

        javax.swing.GroupLayout UsuarioPuntosLayout = new javax.swing.GroupLayout(UsuarioPuntos);
        UsuarioPuntos.setLayout(UsuarioPuntosLayout);
        UsuarioPuntosLayout.setHorizontalGroup(
            UsuarioPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioPuntosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        UsuarioPuntosLayout.setVerticalGroup(
            UsuarioPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioPuntosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(UsuarioPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        Mascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mascota no se.png"))); // NOI18N
        jPanel1.add(Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 200, 200));

        LadoOjitasDerecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Foto de los lados ojitas.jpeg"))); // NOI18N
        LadoOjitasDerecho.setText("jLabel5");
        jPanel1.add(LadoOjitasDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 80, 560));

        LadoOjitasIzquierdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Foto de los lados ojitas.jpeg"))); // NOI18N
        LadoOjitasIzquierdo.setText("Lado ojitas");
        jPanel1.add(LadoOjitasIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 90, 560));

        MensajeLogros.setBackground(new java.awt.Color(148, 193, 50));

        jLabel9.setText("¡Reciclaje completado!");

        javax.swing.GroupLayout MensajeLogrosLayout = new javax.swing.GroupLayout(MensajeLogros);
        MensajeLogros.setLayout(MensajeLogrosLayout);
        MensajeLogrosLayout.setHorizontalGroup(
            MensajeLogrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLogrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        MensajeLogrosLayout.setVerticalGroup(
            MensajeLogrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLogrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(MensajeLogros, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogrosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogrosBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogrosBotonActionPerformed

    private void MiHistorialBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiHistorialBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiHistorialBotonActionPerformed

    private void basuraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basuraMouseClicked
        // TODO add your handling code here:
       //este espacio es para configurar un boton 
       Reciclaje botella = new Reciclaje ();
       botella.setVisible(true);
       dispose();
    }//GEN-LAST:event_basuraMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LadoOjitasDerecho;
    private javax.swing.JLabel LadoOjitasIzquierdo;
    private javax.swing.JButton LogrosBoton;
    private javax.swing.JLabel Mascota;
    private javax.swing.JPanel MensajeLogros;
    private javax.swing.JButton MiHistorialBoton;
    private javax.swing.JButton TiendaBoton;
    private javax.swing.JPanel UsuarioPuntos;
    private javax.swing.JLabel basura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
